// Renders src/content/strings/areas.gen.ts: one import + one entry per `en-<area>.ts` module,
// so adding a content area never edits en.ts (T099, docs/architecture/content-model.md).
// Pure functions; tools/content/index.ts writes the file, strings-registry.test.ts checks it.
import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const STRINGS_DIR = fileURLToPath(new URL('../../src/content/strings/', import.meta.url));
export const REGISTRY_FILE = 'areas.gen.ts';
const AREA_FILE = /^en-([a-z0-9]+(?:-[a-z0-9]+)*)\.ts$/;

/** Area names (`en-<area>.ts` -> `<area>`) in a directory listing, sorted. */
export function areaNames(files: readonly string[]): string[] {
  return files.flatMap((f) => AREA_FILE.exec(f)?.[1] ?? []).sort();
}

/** The area names found in src/content/strings. */
export function scanAreas(dir: string = STRINGS_DIR): string[] {
  return areaNames(readdirSync(dir));
}

/** Registry key: `yak-shave` -> `yakShave`. */
export function camel(area: string): string {
  return area.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** Export name convention: `en-yak-shave.ts` exports `enYakShave`. */
export function exportName(area: string): string {
  const c = camel(area);
  return `en${c.charAt(0).toUpperCase()}${c.slice(1)}`;
}

/** Source of the generated registry module (Biome-formatted). */
export function renderRegistry(areas: readonly string[]): string {
  const imports = areas.map((a) => `import { ${exportName(a)} } from './en-${a}.ts';`);
  const entries = areas.map((a) => `  ${camel(a)}: ${exportName(a)},`);
  const spreads = areas.map((a) => `  ...${exportName(a)},`);
  return [
    '// GENERATED by `npm run content:index` (tools/content/index.ts). Do not edit by hand.',
    '// One entry per src/content/strings/en-<area>.ts module; en.ts spreads `enAreas`.',
    ...imports,
    '',
    '/** Every area string module by area name (completeness and duplicate-key tests). */',
    'export const EN_AREA_MODULES = {',
    ...entries,
    '} as const;',
    '',
    '/** All area strings merged; spread once into `en`. */',
    'export const enAreas = {',
    ...spreads,
    '} as const;',
    '',
  ].join('\n');
}
