// GENERATED by `npm run content:index` (tools/content/index.ts). Do not edit by hand.
// One entry per src/content/strings/en-<area>.ts module; en.ts spreads `enAreas`.
import { enCombat } from './en-combat.ts';
import { enEnemies } from './en-enemies.ts';
import { enEvents } from './en-events.ts';
import { enHarnesses } from './en-harnesses.ts';
import { enLessons } from './en-lessons.ts';
import { enLog } from './en-log.ts';
import { enRunEnd } from './en-run-end.ts';
import { enSkills } from './en-skills.ts';
import { enTools } from './en-tools.ts';
import { enUi } from './en-ui.ts';

/** Every area string module by area name (completeness and duplicate-key tests). */
export const EN_AREA_MODULES = {
  combat: enCombat,
  enemies: enEnemies,
  events: enEvents,
  harnesses: enHarnesses,
  lessons: enLessons,
  log: enLog,
  runEnd: enRunEnd,
  skills: enSkills,
  tools: enTools,
  ui: enUi,
} as const;

/** All area strings merged; spread once into `en`. */
export const enAreas = {
  ...enCombat,
  ...enEnemies,
  ...enEvents,
  ...enHarnesses,
  ...enLessons,
  ...enLog,
  ...enRunEnd,
  ...enSkills,
  ...enTools,
  ...enUi,
} as const;
