// GENERATED by `npm run content:index` (tools/content/index.ts). Do not edit by hand.
// One entry per src/content/strings/en-<area>.ts module; en.ts spreads `enAreas`.
import { enEnemies } from './en-enemies.ts';
import { enEvents } from './en-events.ts';
import { enHarnesses } from './en-harnesses.ts';
import { enLessons } from './en-lessons.ts';
import { enSkills } from './en-skills.ts';
import { enTools } from './en-tools.ts';

/** Every area string module by area name (completeness and duplicate-key tests). */
export const EN_AREA_MODULES = {
  enemies: enEnemies,
  events: enEvents,
  harnesses: enHarnesses,
  lessons: enLessons,
  skills: enSkills,
  tools: enTools,
} as const;

/** All area strings merged; spread once into `en`. */
export const enAreas = {
  ...enEnemies,
  ...enEvents,
  ...enHarnesses,
  ...enLessons,
  ...enSkills,
  ...enTools,
} as const;
