// Combat log lines (docs/game/ux/screens.md "Tooltips and the combat log"). Spread into `en`.
// `log.<kind>` is the verb of one event kind; `log.line` wraps it as
// `[mm:ss.mmm] source -> target: verb (why)`. `ui.log.*` is the panel chrome.

export const enLog = {
  'ui.log.region': 'Combat log',
  'ui.log.title': 'Log',
  'ui.log.filters': 'Show',
  'ui.log.filter.all': 'All',
  'ui.log.filter.damage': 'Damage',
  'ui.log.filter.context': 'Context',
  'ui.log.filter.enemies': 'Enemies',
  'ui.log.lines': 'Log lines',
  'ui.log.count.one': '{n} line',
  'ui.log.count.other': '{n} lines',
  'ui.log.hint': 'Click a line or use ↑ ↓ to rewind',
  'ui.log.empty': 'Waiting for the first event…',
  'log.line': '[{time}] {src} -> {dst}: {verb}',
  'log.line.self': '[{time}] {src}: {verb}',
  'log.why': '{verb} ({why})',
  'log.ref.ctx': 'context',
  'log.ref.sys': 'system',
  'log.ref.summon': 'sub-agent',
  'log.ref.tool': '{name} v{v}',
  'log.why.prime': '{name} prime',
  'log.why.lesson': 'AGENTS.md',
  'log.why.armor': '{n} into armor',
  'log.why.guard': '{n} into Guardrails',
  'log.fight_start': 'fight starts, Deadline {time}',
  'log.spawn': 'joins at {n} Severity',
  'log.spawn.blocked': 'spawn blocked (line full)',
  'log.intent_set': 'readies {intent} ({time})',
  'log.tool_fired': 'fires',
  'log.tool_fired.echo': 'fires, echoes {n}x',
  'log.pipe': 'pipes {time} of charge (chain {chain})',
  'log.charge': '+{time} charge',
  'log.damage': '{n} dmg',
  'log.guard': '+{n} Guardrails ({total})',
  'log.heal': '+{n} heal ({total})',
  'log.tokens.output': '{n}k output',
  'log.tokens.noise': '{n}k noise',
  'log.tokens.removal': '{n}k removed',
  'log.tokens.baseline': '{n}k baseline',
  'log.tokens.report': '{n}k report',
  'log.zone_changed': 'zone {from} -> {to}',
  'log.compaction.auto': 'auto-compaction, Stun {time}',
  'log.compaction.planned': 'planned compaction, Stun {time}',
  'log.compaction.tool': 'compacted, Stun {time}',
  'log.status_on': '{status} for {time}',
  'log.status_off': '{status} ends',
  'log.prime': 'primes +{n}%',
  'log.prime_used': 'spends a +{n}% prime',
  'log.trait': '{trait} {what} {n}',
  'log.trait.grow.sev': 'grows +{n} Severity',
  'log.trait.grow.dmg': 'grows +{n} damage',
  'log.trait.outage.timed_out': 'times out',
  'log.armor_broken': 'armor layer breaks, {n} left',
  'log.enemy_acted': 'uses {intent}',
  'log.redirect': 'redirects the next hit',
  'log.summon': 'starts a sub-agent for {time}',
  'log.summon_end': 'sub-agent reports {n}k',
  'log.resolved': 'resolved by {by}',
  'log.roll': 'rolls {n} ({lo}-{hi})',
  'log.deadline': 'Deadline pressure {n}',
} as const;
