// Run-end summary and AGENTS.md screens (docs/game/ux/onboarding.md "Why did I lose?",
// meta-progression.md "AGENTS.md lessons"). Spread into `en`.

export const enRunEnd = {
  'ui.runend.title.ctrlc': '^C',
  'ui.runend.title.abandoned': '^C',
  'ui.runend.title.shipped': 'Merged to main!',
  'ui.runend.lead.ctrlc': 'Your human pressed Ctrl+C. Trust ran out.',
  'ui.runend.lead.abandoned': 'You pressed Ctrl+C yourself.',
  'ui.runend.lead.shipped': 'The release shipped. Your human closes the laptop, satisfied.',
  'ui.runend.file': '~/run-{seed}.log',
  'ui.runend.cause': 'cause',
  'ui.runend.cause.shipped': 'none, it shipped',
  'ui.runend.cause.abandoned': 'run abandoned',
  'ui.runend.cause.unknown': 'trust ran out outside a fight',
  'ui.runend.cleared': 'fights won',
  'ui.runend.compactions': 'compactions',
  'ui.runend.deadline': 'The Deadline',
  'ui.runend.damage': 'damage taken by source',
  'ui.runend.no_damage': 'No damage taken. Clean run.',
  'ui.runend.zones': 'time per zone, last fight',
  'ui.runend.hint': 'hint',
  'ui.runend.hint.rot':
    'Over 40% of the fight in Rot. Try a lower compaction policy or `summarize`.',
  'ui.runend.hint.throttle': 'Throttled again and again. Mix cooldowns or take Lockfile.',
  'ui.runend.hint.deadline': 'Your build lacked damage: prioritise upgrades.',
  'ui.runend.hint.default': 'Duplicates upgrade a tool to v2 and v3. Depth beats breadth.',
  'ui.runend.next': 'Open AGENTS.md',
  'ui.runend.back': 'Back to title',
  'ui.agents.title': 'AGENTS.md',
  'ui.agents.fm.title': 'title',
  'ui.agents.fm.summary': 'summary',
  'ui.agents.fm.summary_value': 'What this agent learned the hard way.',
  'ui.agents.fm.lines': 'lines',
  'ui.agents.fm.cost': 'cost',
  'ui.agents.fm.cost_value': '1 token per line, every fight',
  'ui.agents.heading': '# Lessons',
  'ui.agents.empty': '<!-- empty -->',
  'ui.agents.offer': '<!-- offered after this run: pick one -->',
  'ui.agents.write': 'write',
  'ui.agents.replace': 'replace line {line}',
} as const;
