// Skill and memory names, flavour lines and custom-handler texts. Spread into `en`.
// Lines are generated by describeRule from the rule data (src/content/text.ts).

export const enSkills = {
  'skill.unix_philosophy.name': 'Unix Philosophy',
  'skill.unix_philosophy.flavour': 'Do one thing well. Then pipe it.',
  'skill.inline_suggestions.name': 'Inline Suggestions',
  'skill.inline_suggestions.flavour': 'Ghost text, and it is usually right.',
  'skill.grep_first.name': 'Grep First',
  'skill.grep_first.flavour': 'Look before you leap. Then leap.',
  'skill.lockfile.name': 'Lockfile',
  'skill.lockfile.flavour': 'Pinned. Frozen. Unbothered.',
  'skill.summarizer.name': 'Summarizer',
  'skill.summarizer.flavour': 'Forgets the details, keeps the vibe.',
  'skill.long_context_training.name': 'Long-Context Training',
  'skill.long_context_training.flavour': 'It read the whole thing. It remembers some of it.',
  'skill.feedback_loop.name': 'Feedback Loop',
  'skill.feedback_loop.flavour': 'The output is the input. The output is the input.',
  'skill.rubber_duck.name': 'Rubber Duck',
  'skill.rubber_duck.flavour': 'Explains the bug by listening.',

  'memory.gitignore.name': '.gitignore',
  'memory.gitignore.flavour': 'node_modules never happened.',
  'memory.cache.name': 'Cache',
  // joke: "cache invalidation" is one of the two hard problems in computer science.
  'memory.cache.flavour': 'Fast, until it is stale.',
  'memory.long_context.name': 'Long Context',
  'memory.long_context.flavour': 'Room for everything, attention for less.',
  'memory.keyboard_shortcuts.name': 'Keyboard Shortcuts',
  'memory.keyboard_shortcuts.flavour': 'Ctrl+Z is a lifestyle.',

  // Custom handler texts (named in rules as `custom` effects).
  'handler.rot_no_slow': 'Rot no longer slows your tools (noise is still doubled)',
  'handler.feedback_loop': 'your rightmost tool pipes 1000 ms into your leftmost tool',
  'handler.web_ignores_outage': 'your Web tools ignore Outage',
} as const;
