// Tool names and flavour lines (docs/game/content/tools.md "Flavour lines (M1 tools)").
// Spread into `en`. Names are the tool ids; lines are generated by describeTool.

export const enTools = {
  'tool.grep.name': 'grep',
  'tool.grep.flavour': 'Finds the needle, ignores the haystack.',
  'tool.cat.name': 'cat',
  'tool.cat.flavour': 'Prints everything. Everything.',
  'tool.read_file.name': 'read_file',
  'tool.read_file.flavour': 'Reads the whole file before touching it. Suspiciously diligent.',
  'tool.sed.name': 'sed',
  // joke: a global search-and-replace that may break more than it fixes.
  'tool.sed.flavour': 'Fixes it in every file at once. Hopefully.',
  'tool.edit_file.name': 'edit_file',
  'tool.edit_file.flavour': 'Surgical. Slow.',
  'tool.autocomplete.name': 'autocomplete',
  'tool.autocomplete.flavour': 'Tab, tab, tab.',
  'tool.lint.name': 'lint',
  'tool.lint.flavour': 'Catches it before the human does.',
  'tool.run_tests.name': 'run_tests',
  // joke: a passing (green) test run is more mood than proof.
  'tool.run_tests.flavour': 'Green is a feeling.',
  'tool.retry_with_backoff.name': 'retry_with_backoff',
  // joke: exponential backoff doubles the wait after each failed retry.
  'tool.retry_with_backoff.flavour': 'Wait 1 s, 2 s, 4 s…',
  'tool.brute_force.name': 'brute_force',
  'tool.brute_force.flavour': 'More context, more force.',
  'tool.web_search.name': 'web_search',
  'tool.web_search.flavour': 'Somebody must have had this problem.',
  'tool.summarize.name': 'summarize',
  // joke: "too long; didn't read", the shortest possible summary.
  'tool.summarize.flavour': 'TL;DR.',
} as const;
