// Shell and screen chrome (docs/game/ux/screens.md). Spread into `en`; keys `ui.<area>.<name>`.

export const enUi = {
  'ui.title.name': 'Loop Engineer',
  'ui.title.seed': 'Seed',
  'ui.title.new_run': 'New run',
  'ui.title.sandbox': 'Combat sandbox',
  'ui.title.prompt': '$ loop-engineer',
  'ui.title.tagline': 'You are an AI agent. Ship the release before they press Ctrl+C.',
  'ui.harness.title': 'Select a harness',
  'ui.harness.hint': 'Arrow keys choose, Enter starts the run, Esc goes back.',
  'ui.harness.file': '~/.config/{id}.yml',
  'ui.harness.difficulty': 'Difficulty: {level}',
  'ui.harness.recommended': 'Recommended for your first run',
  'ui.harness.start': 'Start run',
  'ui.harness.back': 'Back',
  'ui.cfg.window': 'window',
  'ui.cfg.speed': 'speed',
  'ui.cfg.accuracy': 'accuracy',
  'ui.cfg.trust': 'trust',
  'ui.cfg.base': 'base_weight',
  'ui.cfg.slots': 'slots',
  'ui.cfg.tools': 'tools',
  'ui.cfg.skills': 'skills',
  'ui.cfg.accuracy.high': 'high',
  'ui.cfg.accuracy.normal': 'normal',
  'ui.cfg.accuracy.low': 'low',
  'ui.cfg.slots_value': '{tools} tools, {skills} skills, {memory} memory',
  'ui.prompt.title': 'Pick a system prompt',
  'ui.prompt.tip': 'Prompts cost context. Smaller is leaner.',
  'ui.prompt.quote': '“{text}”',
  'ui.prompt.weight': 'weight {n}',
  'ui.shell.breadcrumb': 'phase-{phase}/{mode}',
  'ui.shell.seed': 'seed {seed}',
  'ui.shell.explorer': 'Explorer',
  'ui.shell.terminal': 'Terminal',
  'ui.shell.error': 'error: {code}',
  'ui.status.trust': 'Trust',
  'ui.status.credits': 'Credits',
  'ui.status.ctx': 'ctx',
  'ui.status.phase': 'P{phase}',
  'ui.status.speed': '{speed}x',
  'ui.screen.todo': 'No screen for {mode} yet.',
  'ui.action.continue': 'Continue',
  'ui.action.pick_prompt': 'Pick {name}',
  'ui.action.travel': 'Go to {node}',
  'ui.action.pick_reward': 'Take card {n}',
  'ui.action.skip_reward': 'Skip (+{credits} Credits)',
  'ui.action.discard': 'Discard {item}',
  'ui.action.buy': 'Buy offer {n}',
  'ui.action.sell': 'Sell {item}',
  'ui.action.reroll': 'Reroll',
  'ui.action.leave_shop': 'Leave the registry',
  'ui.action.abandon': 'Abandon run',
  'ui.action.pick_lesson': 'Write lesson {n} to AGENTS.md',
  'ui.action.pick_lesson_replace': 'Write lesson {n} over line {line}',
  'ui.action.skip_lesson': 'Keep AGENTS.md as it is',
} as const;
