// Shell and screen chrome (docs/game/ux/screens.md). Spread into `en`; keys `ui.<area>.<name>`.

export const enUi = {
  'ui.title.name': 'Loop Engineer',
  'ui.title.seed': 'Seed',
  'ui.title.new_run': 'New run',
  'ui.title.sandbox': 'Combat sandbox',
  'ui.title.prompt': '$ loop-engineer',
  'ui.title.tagline': 'You are an AI agent. Ship the release before they press Ctrl+C.',
  'ui.harness.title': 'Select a harness',
  'ui.harness.hint': 'Arrow keys choose, Enter starts the run, Esc goes back.',
  'ui.harness.file': '~/.config/{id}.yml',
  'ui.harness.difficulty': 'Difficulty: {level}',
  'ui.harness.recommended': 'Recommended for your first run',
  'ui.harness.start': 'Start run',
  'ui.harness.back': 'Back',
  'ui.cfg.window': 'window',
  'ui.cfg.speed': 'speed',
  'ui.cfg.accuracy': 'accuracy',
  'ui.cfg.trust': 'trust',
  'ui.cfg.base': 'base_weight',
  'ui.cfg.slots': 'slots',
  'ui.cfg.tools': 'tools',
  'ui.cfg.skills': 'skills',
  'ui.cfg.accuracy.high': 'high',
  'ui.cfg.accuracy.normal': 'normal',
  'ui.cfg.accuracy.low': 'low',
  'ui.cfg.slots_value': '{tools} tools, {skills} skills, {memory} memory',
  'ui.prompt.title': 'Pick a system prompt',
  'ui.prompt.tip': 'Prompts cost context. Smaller is leaner.',
  'ui.prompt.quote': '“{text}”',
  'ui.prompt.weight': 'weight {n}',
  'ui.shell.breadcrumb': 'phase-{phase}/{name}',
  'ui.shell.location': 'Location',
  'ui.shell.row': 'row {row}',
  'ui.shell.boss': 'release',
  'ui.phase.1': 'implement',
  'ui.phase.2': 'test',
  'ui.phase.3': 'deploy',
  'ui.shell.seed': 'seed {seed}',
  'ui.shell.explorer': 'Explorer',
  'ui.shell.terminal': 'Terminal',
  'ui.shell.error': 'error: {code}',
  'ui.status.trust': 'Trust',
  'ui.status.credits': 'Credits',
  'ui.status.ctx': 'ctx',
  'ui.status.phase': 'P{phase}',
  'ui.status.speed': '{speed}x',
  'ui.map.title': 'Route to the release',
  'ui.map.hint': 'Arrow keys move, Enter travels. Hover or focus any node to inspect it.',
  'ui.map.nodes': 'Map nodes',
  'ui.map.legend': 'Legend',
  'ui.map.preview': '{type}: {enemies}',
  'ui.map.node': '{preview}, {where}, {state}',
  'ui.map.travel': 'Enter or click to travel',
  'ui.map.state.current': 'you are here',
  'ui.map.state.visited': 'visited',
  'ui.map.state.next': 'reachable',
  'ui.map.state.ahead': 'ahead',
  'ui.map.state.gone': 'out of reach',
  'ui.node.task.name': 'Task',
  'ui.node.task.line': 'A fight from this phase.',
  'ui.node.critical_bug.name': 'Critical Bug',
  'ui.node.critical_bug.line': 'An elite fight. The enemies stay hidden; the loot is better.',
  'ui.node.registry.name': 'Package Registry',
  'ui.node.registry.line': 'A shop: buy, sell and prune tools.',
  'ui.node.standup.name': 'Standup',
  'ui.node.standup.line': 'An event with replies and exact outcomes.',
  'ui.node.idle_cycle.name': 'Idle Cycle',
  'ui.node.idle_cycle.line': 'Rest: restore Trust or upgrade one tool.',
  'ui.node.free_tier.name': 'Free Tier',
  'ui.node.free_tier.line': 'Unbox one random Memory.',
  'ui.node.release.name': 'Release',
  'ui.node.release.line': 'The boss. Resolve it to ship this phase.',
  'ui.reward.title': 'PR ready to merge',
  'ui.reward.hint': 'Pick one change to merge, or skip for credits.',
  'ui.reward.cards': 'Changes',
  'ui.reward.file': 'diff --git a/{kind} b/{kind}',
  'ui.reward.kind.tool': 'tool',
  'ui.reward.kind.skill': 'skill',
  'ui.reward.kind.memory': 'memory',
  'ui.reward.new': 'new',
  'ui.reward.upgrade': '{from} → {to}',
  'ui.reward.rarity.common': 'common',
  'ui.reward.rarity.uncommon': 'uncommon',
  'ui.reward.rarity.rare': 'rare',
  'ui.reward.receipt': 'Receipt',
  'ui.reward.receipt.reward': 'Reward',
  'ui.reward.receipt.interest': 'Interest',
  'ui.reward.receipt.total': 'Total',
  'ui.reward.skip': 'Skip (+{credits} Credits)',
  'ui.discard.title': 'No space left',
  'ui.discard.hint': 'Drop one item to make room for {item}, or discard the new one.',
  'ui.discard.gained': 'Discard the new {item}',
  'ui.discard.slot': 'Discard {item} ({where})',
  'ui.discard.where.tool': 'tool slot {n}',
  'ui.discard.where.skill': 'skill slot {n}',
  'ui.discard.where.memory': 'memory slot {n}',
  'ui.discard.where.stash': 'stash {n}',
  'ui.discard.items': 'Items to discard',
  'ui.shop.title': 'Package Registry',
  'ui.shop.hint': 'Install packages, reroll the list, or sell what you no longer need.',
  'ui.shop.offers': 'Packages',
  'ui.shop.credits': 'Credits: {n}',
  'ui.shop.sale': 'SALE',
  'ui.shop.sold': 'installed',
  'ui.shop.need': 'Need {n} more Credits',
  'ui.shop.price': '$ {n}',
  'ui.shop.reroll': 'Reroll ($ {cost})',
  'ui.shop.leave': 'Leave the registry',
  'ui.shop.sell.title': 'Sell from your build',
  'ui.shop.sell.item': 'Sell {item} (+{n} Credits)',
  'ui.shop.err.last_tool': 'An agent with no tools is a chatbot',
  'ui.item.version': 'v{n}',
  'ui.item.tool_version': '{name} v{n}',
  'ui.screen.todo': 'No screen for {mode} yet.',
  'ui.action.continue': 'Continue',
  'ui.action.pick_prompt': 'Pick {name}',
  'ui.action.travel': 'Go to {node}',
  'ui.action.pick_reward': 'Take card {n}',
  'ui.action.skip_reward': 'Skip (+{credits} Credits)',
  'ui.action.discard': 'Discard {item}',
  'ui.action.buy': 'Buy offer {n}',
  'ui.action.sell': 'Sell {item}',
  'ui.action.reroll': 'Reroll',
  'ui.action.leave_shop': 'Leave the registry',
  'ui.action.rest_heal': 'Rest: heal 30% Trust',
  'ui.action.rest_upgrade': 'Rest: upgrade tool {n}',
  'ui.action.take_treasure': 'Take the free memory',
  'ui.action.choose_event': 'Choose option {n}',
  'ui.action.abandon': 'Abandon run',
  'ui.action.pick_lesson': 'Write lesson {n} to AGENTS.md',
  'ui.action.pick_lesson_replace': 'Write lesson {n} over line {line}',
  'ui.action.skip_lesson': 'Keep AGENTS.md as it is',
} as const;
